name: Backend deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update Lambda code
        working-directory: backend
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          LAMBDA_NAME: ${{ vars.LAMBDA_NAME }}
        run: |
          mkdir -p build
          cp -r *.py build
          cd build
          zip lambda.zip -r .
          aws lambda update-function-code --function-name $LAMBDA_NAME --zip-file fileb://./lambda.zip --region $AWS_REGION